### ISSUE TITLE
What is the current status of the project?

### ISSUE THREAD

**Issue by gavr123456789** [eugals/GTKAndroid#4]
I see a fork that was updated 3 months ago, are there any plans to continue working?  
The idea of running GTK apps on Android sounds very cool. Especially with the advent of LibHandy, I think the naivety of the view can be solved with the help of themes.

**Comment by eugals** [comment]
All the development is frozen on my side at present.
And unfortunately I don't have time or interest in unfreezing it.
This project was never the primary focus to me. It was supposed to be come the first milestone for another app I was working on then. And at some point both architecture and the design of that other app had diverted from my original vision that far so I no longer feel I need that GTKAndroid solution.

I'd be happy to assists if someone forks this repo and continues from where I stopped.

**Comment by roke-julian-lockhart** [comment]
@gavr123456789, is "http://docs.gtk.org/gtk4/broadway.html" adequate replacement?
