### ISSUE TITLE
python clibs/getLibs.py script fails on freetype library

### ISSUE THREAD

**Issue by ghost** [eugals/GTKAndroid#5]
Like the title says.

Solution:

Comment out line 256 which currently reads:
`dl.download("freetype/distsrc", "http://download.savannah.gnu.org/releases/freetype/freetype-2.5.4.tar.bz2") `

And create a line after it that reads:
`dl.download("freetype/distsrc", "https://download.savannah.gnu.org/releases/freetype/freetype-old/freetype-2.5.4.tar.bz2") `
 
as the repo directory structure appears to have changed.

EDIT: I noticed the domain in the update is different as well, and I have no idea of the security implications of that, so heads up fair warning, I used it.

EDIT2: found the "gnu.org" domain link and updated again. Relax security neck hairs a little perhaps.

**Comment by eugals** [comment]
@gnurdware thanks for your input!

I've modified `getLibs.py` and it seems to work as expected now.
